/* Flash — viewers.js : non-HTML rendering (pdf/image/video/audio/text). */
(function (global) {
  "use strict";

  function frameFor(tab) {
    return document.getElementById("frame-" + tab.id);
  }

  // Styling comes ONLY from css/flash.css [standalone-docs], injected here
  // as window.FlashInjectedCSS (generated by tools/build-single-file.py).
  // Never write raw CSS in these templates.
  function docCss() {
    return (global.FlashInjectedCSS || "");
  }

  function showBlobInFrame(tab, blob, kind) {
    const f = frameFor(tab);
    const objUrl = URL.createObjectURL(blob);
    const base = tab.url;
    let inner = "";
    if (kind === "image") {
      inner = `<img id="v" class="fmedia-img" src="${objUrl}">`;
    } else if (kind === "video") {
      inner = `<video id="v" class="fmedia-video" src="${objUrl}" controls autoplay></video>`;
    } else if (kind === "audio") {
      inner = `<audio id="v" class="fmedia-audio" src="${objUrl}" controls autoplay></audio>`;
    }
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${docCss()}</style></head>
      <body class="fcenter">
      <div class="fbar"><span class="vbrand">${global.FlashIcons.svg("zap", 14)} Flash viewer — ${global.FlashUtil.escapeHtml(base)}</span>
      <a class="flink" href="${objUrl}" download>Download</a>
      <button class="fbtn" onclick="document.getElementById('v').style.transform=(document.getElementById('v').style.transform?'':'scale(1.5)')">Zoom</button></div>
      ${inner}<script>parent.postMessage({__flash:1,tab:${JSON.stringify(tab.id)},type:"title",data:{title:"[media] "+${JSON.stringify(base)}}},"*");<\/script>
      </body></html>`;
    f.removeAttribute("srcdoc");
    f.srcdoc = html;
    f._lastAssign = Date.now();
    try { global.FlashTabs.noteFrameAssign(f); } catch {}
    f.style.display = "";
  }

  /* FEATURE:pdf:begin */
  async function showPdf(tab, bytes, url) {
    const f = frameFor(tab);
    // Use in-iframe PDF.js from CDN; bytes passed as base64 to avoid 2nd fetch.
    const b64 = global.FlashUtil.b64encode(bytes);
    const pdfJs = global.FlashConfig.PDFJS_CDN.js;
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${docCss()}</style></head>
      <body class="fdoc">
      <div class="fbar-top"><span class="vbrand">${global.FlashIcons.svg("zap", 14)} Flash PDF — ${global.FlashUtil.escapeHtml(url)}</span>
      <button class="fbtn" id="prev">‹</button><span id="pg">1 / ?</span><button class="fbtn" id="next">›</button>
      <button class="fbtn" id="zin">Zoom+</button><button class="fbtn" id="zout">Zoom−</button></div>
      <div class="fpages" id="pages"></div>
      <script type="module">
      import * as pdfjs from ${JSON.stringify(pdfJs)};
      const raw=Uint8Array.from(atob(${JSON.stringify(b64)}),c=>c.charCodeAt(0));
      const pdf=await pdfjs.getDocument({data:raw}).promise;
      let page=1,scale=1.3;const box=document.getElementById("pages"),lbl=document.getElementById("pg");
      async function draw(){box.innerHTML="";const p=await pdf.getPage(page);const vp=p.getViewport({scale});
        const cv=document.createElement("canvas");cv.width=vp.width;cv.height=vp.height;
        await p.render({canvasContext:cv.getContext("2d"),viewport:vp}).promise;box.appendChild(cv);lbl.textContent=page+" / "+pdf.numPages;}
      document.getElementById("prev").onclick=()=>{if(page>1){page--;draw();}};
      document.getElementById("next").onclick=()=>{if(page<pdf.numPages){page++;draw();}};
      document.getElementById("zin").onclick=()=>{scale+=0.2;draw();};
      document.getElementById("zout").onclick=()=>{scale=Math.max(0.5,scale-0.2);draw();};
      draw();parent.postMessage({__flash:1,tab:${JSON.stringify(tab.id)},type:"title",data:{title:"[pdf] "+${JSON.stringify(url)}}},"*");
      <\/script></body></html>`;
    f.srcdoc = html;
    f._lastAssign = Date.now();
    try { global.FlashTabs.noteFrameAssign(f); } catch {}
    f.style.display = "";
  }
  /* FEATURE:pdf:end */

  async function showText(tab, bytes, url, contentType) {
    const f = frameFor(tab);
    let text = "";
    try { text = new TextDecoder("utf-8", { fatal: false }).decode(bytes); }
    catch { text = "[binary]"; }
    const esc = global.FlashUtil.escapeHtml(text.slice(0, 500000));
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${docCss()}</style></head>
      <body class="fdoc-mono">
      <div class="fbar-top"><span class="vbrand">${global.FlashIcons.svg("zap", 14)} Flash text — ${global.FlashUtil.escapeHtml(url)} <span class="fmuted">${global.FlashUtil.escapeHtml(contentType || "")} · ${bytes.length} bytes</span></span></div>
      <pre class="ftext">${esc}</pre>
      <script>parent.postMessage({__flash:1,tab:${JSON.stringify(tab.id)},type:"title",data:{title:"[text] "+${JSON.stringify(url)}}},"*");<\/script>
      </body></html>`;
    f.srcdoc = html;
    f._lastAssign = Date.now();
    try { global.FlashTabs.noteFrameAssign(f); } catch {}
    f.style.display = "";
  }

  // Dedicated video theater: title bar, maximized stage, speed + fullscreen.
  function showVideo(tab, blob, url) {
    const f = frameFor(tab);
    const objUrl = URL.createObjectURL(blob);
    const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${docCss()}</style></head>
      <body class="fdoc" style="display:flex;flex-direction:column;height:100vh;overflow:hidden;">
      <div class="fbar-top"><span class="vbrand">${global.FlashIcons.svg("zap", 14)} Flash video — ${global.FlashUtil.escapeHtml(url)}</span>
      <a class="flink" href="${objUrl}" download>Download</a></div>
      <div style="flex:1;display:flex;align-items:center;justify-content:center;padding:16px;min-height:0;">
        <video id="v" src="${objUrl}" controls autoplay style="max-width:96vw;max-height:100%;width:auto;background:#000;border-radius:8px;"></video>
      </div>
      <div class="fbar" style="justify-content:center;gap:12px;border-radius:0;border-left:0;border-right:0;border-bottom:0;">
        <button class="fbtn" id="pp">Pause</button>
        <button class="fbtn" id="spd">1×</button>
        <button class="fbtn" id="fs">Fullscreen</button>
      </div>
      <script>var v=document.getElementById("v");
      document.getElementById("pp").onclick=function(){if(v.paused){v.play();this.textContent="Pause";}else{v.pause();this.textContent="Play";}};
      var speeds=[1,1.25,1.5,2,0.5],si=0;
      document.getElementById("spd").onclick=function(){si=(si+1)%speeds.length;v.playbackRate=speeds[si];this.textContent=speeds[si]+"\\u00d7";};
      document.getElementById("fs").onclick=function(){try{if(v.requestFullscreen)v.requestFullscreen();else if(v.webkitEnterFullscreen)v.webkitEnterFullscreen();}catch(e){}};
      parent.postMessage({__flash:1,tab:${JSON.stringify(tab.id)},type:"title",data:{title:"[video] "+${JSON.stringify(url)}}},"*");<\/script>
      </body></html>`;
    f.removeAttribute("srcdoc");
    f.srcdoc = html;
    f.style.display = "";
    f._lastAssign = Date.now();
    try { global.FlashTabs.noteFrameAssign(f); } catch {}
  }

  async function renderNonHtml(tab, kind, resp) {
    const ct = (resp.headers["content-type"] || "").split(";")[0];
    let s = {};
    try { s = global.FlashStore.getSettings(); } catch {}
    const on = (k, fb) => (s[k] == null ? fb : s[k] !== false);
    function downloadBlob(blob, name) {
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = name;
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(a.href), 10000);
    }
    if (kind === "pdf") {
      if (!on("pdfViewer", true)) {
        downloadBlob(new Blob([resp.body], { type: ct || "application/pdf" }),
          (tab.url.split("/").pop() || "document.pdf").split("?")[0] || "document.pdf");
        global.FlashTabs.setTitle(tab, `[pdf] ${resp.finalUrl}`);
        return;
      }
      /* FEATURE:pdf:begin */
      if (resp.body.length > 25 * 1024 * 1024) {
        // Huge PDFs: offer download instead of in-memory render.
        showBlobInFrame(tab, new Blob([resp.body], { type: "application/pdf" }), "image");
      } else {
        await showPdf(tab, resp.body, resp.finalUrl);
      }
      return;
      /* FEATURE:pdf:end */
      // No viewer in this build: download the file instead.
      const blob = new Blob([resp.body], { type: ct || "application/pdf" });
      const a = document.createElement("a");
      a.href = URL.createObjectURL(blob);
      a.download = (tab.url.split("/").pop() || "document.pdf").split("?")[0] || "document.pdf";
      document.body.appendChild(a);
      a.click();
      a.remove();
      setTimeout(() => URL.revokeObjectURL(a.href), 10000);
      global.FlashTabs.setTitle(tab, `[pdf] ${resp.finalUrl}`);
      return;
    } else if (kind === "video") {
      if (!on("videoViewer", true)) {
        downloadBlob(new Blob([resp.body], { type: ct || "video/mp4" }),
          (tab.url.split("/").pop() || "video").split("?")[0] || "video");
      } else {
        const blob = new Blob([resp.body], { type: ct || "video/mp4" });
        showVideo(tab, blob, resp.finalUrl);
      }
    } else if (kind === "image" || kind === "audio") {
      const key = kind === "image" ? "imageViewer" : "audioViewer";
      if (!on(key, true)) {
        downloadBlob(new Blob([resp.body], { type: ct || "application/octet-stream" }),
          (tab.url.split("/").pop() || kind).split("?")[0] || kind);
      } else {
        const blob = new Blob([resp.body], { type: ct || "application/octet-stream" });
        showBlobInFrame(tab, blob, kind);
      }
    } else if (kind === "text") {
      if (!on("textViewer", true)) {
        downloadBlob(new Blob([resp.body], { type: ct || "text/plain" }),
          (tab.url.split("/").pop() || "file.txt").split("?")[0] || "file.txt");
      } else {
        await showText(tab, resp.body, resp.finalUrl, ct);
      }
    } else {
      // Unknown MIME: auto-download toggle decides between download and silent fail.
      if (on("autoDownloadUnknown", true)) {
        downloadBlob(new Blob([resp.body], { type: ct || "application/octet-stream" }),
          (tab.url.split("/").pop() || "download").split("?")[0] || "download");
      } else {
        const f = frameFor(tab);
        f.srcdoc = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${docCss()}</style></head><body class="fcard-page"><div class="fcard"><div class="fcard-alert"><span class="fcard-ic">${global.FlashIcons.svg("file", 20)}</span><div><h3>Download blocked by settings</h3><div class="fcard-url">${global.FlashUtil.escapeHtml(resp.finalUrl || tab.url)}</div></div></div><p class="fcard-tip">Turn on “Auto-download unknown file types” in Settings → Files &amp; Media to fetch files like this one.</p></div></body></html>`;
        f._lastAssign = Date.now();
    try { global.FlashTabs.noteFrameAssign(f); } catch {}
        f.style.display = "";
      }
    }
    global.FlashTabs.setTitle(tab, `[${kind}] ${resp.finalUrl}`);
  }

  global.FlashViewers = { renderNonHtml };
})(window);
