#!/usr/bin/env python3
"""Flash — build-single-file.py
Inline css/ + js/ into FlashNext.html (repo root) so Flash is ONE file:
download it, double-click it (file://), share it on USB, paste it into any
static host, wrap it in about:blank / blob: / data:.

Source shell: shell.html + css/ + js/. Never edit FlashNext.html by hand —
it is generated output (like dist/). Edit sources, rebuild.

Primary output:  FlashNext.html             (repo root — open via file://, no server)

Usage:
    python3 tools/build-single-file.py [--out some/other.html]

Notes:
  - WASM engines (Epoxy, libcurl.js) + pdf.js stay on CDN on purpose:
    inlining ~2-3MB of WASM would bloat the file. They load lazily via
    classic <script> / ESM CDN URLs (both file://-safe: https subresources
    load fine from a file:// page) on first navigation. No local server,
    no relative-path fetches, no ServiceWorkers — ever.
  - libcurl.js uses the SINGLE-FILE build (libcurl_full.js, WASM inlined as
    base64 upstream) so file:// never needs a sibling .wasm download.
"""
import pathlib
import sys
import json

ROOT = pathlib.Path(__file__).resolve().parent.parent
CSS = ROOT / "css" / "flash.css"
INDEX = ROOT / "shell.html"
INJECTED_JS = ROOT / "js" / "injected-css.js"
BUILDINFO_JS = ROOT / "js" / "build-info.js"
def extract_standalone_css(css: str) -> str:
    """Pull the standalone-docs section out of flash.css.

    Sandboxed iframe documents can't inherit the parent stylesheet, so this
    exact section becomes window.FlashInjectedCSS (js/injected-css.js) and
    every srcdoc template inlines it as its <style>. Single source of truth.
    """
    i = css.find("standalone-docs:begin")
    assert i != -1, "standalone-docs begin marker missing in flash.css"
    comment_end = css.find("*/", i)
    assert comment_end != -1, "unterminated standalone-docs header comment"
    j = css.find("standalone-docs:end", comment_end)
    assert j != -1, "standalone-docs end marker missing in flash.css"
    # back up to the start of the end-marker's line so no comment leaks in
    line_start = css.rfind("\n", comment_end, j) + 1
    chunk = css[comment_end + 2:line_start].strip()
    assert ".fdoc" in chunk and ".fcard" in chunk, "standalone-docs section looks empty"
    assert "var(--" not in chunk, "standalone-docs must use literal values (no host tokens)"
    return chunk


def write_injected_js(chunk: str) -> None:
    INJECTED_JS.write_text(
        "/* GENERATED — do not edit by hand. Source: css/flash.css "
        "[standalone-docs section]. Regenerated by tools/build-single-file.py "
        "on every build. Exposes window.FlashInjectedCSS for iframe srcdocs. */\n"
        "window.FlashInjectedCSS = " + json.dumps(chunk) + ";\n",
        encoding="utf-8",
    )
def write_build_info() -> dict:
    """Build number + tree state + timestamp. Number = commit count, so it only
    grows; state is 'stable' on a clean tree, 'dirty' with uncommitted changes.
    The timestamp lets users confirm which bundle they're actually running."""
    import subprocess
    from datetime import datetime, timezone
    n, state = 0, "dev"
    try:
        n = int(subprocess.run(
            ["git", "rev-list", "--count", "HEAD"], cwd=ROOT,
            capture_output=True, text=True, timeout=15,
        ).stdout.strip())
        dirty = subprocess.run(
            ["git", "status", "--short"], cwd=ROOT,
            capture_output=True, text=True, timeout=15,
        ).stdout.strip()
        state = "dirty" if dirty else "stable"
    except Exception:
        pass
    info = {"n": n, "state": state, "at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
    BUILDINFO_JS.write_text(
        "/* GENERATED — do not edit by hand. Written by tools/build-single-file.py "
        "on every build. Exposes window.FlashBuild = { n, state, at }. */\n"
        "window.FlashBuild = " + json.dumps(info) + ";\n",
        encoding="utf-8",
    )
    return info


JS_ORDER = [
    "js/config.js",
    "js/build-info.js",
    "js/injected-css.js",
    "js/icons.js",
    "js/i18n.js",
    "js/util.js",
    "js/store.js",
    "js/cookies.js",
    "js/log.js",
    "js/engine.js",
    "js/sandbox.js",
    "js/render.js",
    "js/adblock.js",
    "js/bookmarks-history.js",
    "js/tabs.js",
    "js/viewers.js",
    "js/inspector.js",
    "js/settings.js",
    "js/changelog.js",
    "js/internal.js",
    "js/yt.js",
    "js/assistant.js",
    "js/extensions.js",
    "js/suggest.js",
    "js/tutorial.js",
    "js/app.js",
]

BANNER = "<!-- FlashNext standalone — single file, open directly. Built from shell.html + css/ + js/. -->\n"


def build() -> str:
    css = CSS.read_text(encoding="utf-8")
    write_injected_js(extract_standalone_css(css))
    info = write_build_info()
    print(f"build #{info['n']} {info['state']}")
    index = INDEX.read_text(encoding="utf-8")

    # Inline stylesheet
    tag_css = '<link rel="stylesheet" href="css/flash.css">'
    assert tag_css in index, "stylesheet tag missing in shell.html"
    index = index.replace(tag_css, "<style>\n" + css + "\n</style>")

    # Inline each module script (keep execution order). Escape `</script`.
    # Emit module markers so patcher.html can replace whole modules.
    for rel in JS_ORDER:
        src = (ROOT / rel).read_text(encoding="utf-8")
        src = src.replace("</script", "<\\/script")
        tag = f'<script src="{rel}"></script>'
        assert tag in index, f"missing tag for {rel}"
        block = f"<!-- MODULE:{rel} -->\n<script>\n" + src + "\n</script>"
        index = index.replace(tag, block)

    index = index.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + BANNER, 1)
    return index


def verify(html: str) -> None:
    # 1) No relative subresource loads left (file:// has no server to serve them).
    for needle in ['src="js/', 'src="css/', 'href="css/', 'href="js/']:
        assert needle not in html, f"relative reference left in bundle: {needle}"
    # 2) Both WASM engines referenced via https CDN (file://-safe).
    assert "libcurl" in html and "cdn.jsdelivr.net/npm/libcurl.js" in html, \
        "libcurl.js CDN reference missing"
    assert "epoxy" in html.lower() and "cdn.jsdelivr.net/npm/@mercuryworkshop/epoxy-tls" in html, \
        "epoxy CDN reference missing"
    # 3) No service worker registration, ever.
    assert "serviceWorker.register" not in html, "service worker registration found!"
    assert "FlashNext" in html or "Flash" in html


def main():
    html = build()
    verify(html)

    outs = [ROOT / "FlashNext.html"]
    if "--out" in sys.argv:
        outs = [ROOT / sys.argv[sys.argv.index("--out") + 1]]

    for out in outs:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(html, encoding="utf-8")
        print(f"wrote {out} ({out.stat().st_size/1024:.1f} KB)")

    print("OK: standalone ready. Double-click FlashNext.html (file://) — no server needed.")
    print("    Engines lazy-load from CDN on first navigation: libcurl_full.js + epoxy-bundled.js.")


if __name__ == "__main__":
    main()
